[package]
name = "derives"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.37"
proc-macro2 = "1.0.67"
time = { version = "0.3.29", features = ["serde", "serde-human-readable"] }